#10 handle save for answer_edit view
DigiKlausur/ccm_components pull request #13
Opened 2019-02-18 11:25 UTC by Suppi14

- Persist answer to DB : answer_edit.js

2019-02-18 12:08 UTC, minhnh requested changes
Only minor changes. If you can show me how it works on your computer, we can merge this.

2019-02-18 12:08 UTC, minhnh commented on answer_edit/ccm.answer_edit.js
> +        // const qaId = null;
please remove commented out code

2019-02-18 12:08 UTC, minhnh commented on answer_edit/ccm.answer_edit.js
> +            console.log(qaData[qaId]['question']);
please remove debug code

2019-02-18 12:08 UTC, minhnh commented on answer_edit/ccm.answer_edit.js
> +         renderQAPairs();
remove this unnecessary change

2019-02-18 12:08 UTC, minhnh commented on answer_edit/ccm.answer_edit.js
> +         }
remove unnecessary change

2019-02-18 12:12 UTC, Suppi14 commented
Yes. I can show the working

2019-02-25 14:34 UTC, minhnh approved these changes

2019-02-25 14:34 UTC, merged